# Generated by Django 3.0.2 on 2020-01-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentderData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.TextField(null=True)),
                ('html_code', models.TextField(null=True)),
                ('row_structure', models.TextField(null=True)),
            ],
        ),
    ]
